steps:
  # - name: node:16
  #   id: install
  #   entrypoint: yarn
  #   args: ['install']
  #   waitFor: ['-']
  # TODO add when tests are added
  # - name: node:16
  #   entrypoint: yarn
  #   args: ['test']
  #   waitFor: ['install']

  - name: 'gcr.io/kaniko-project/executor:latest'
    args: ['--destination=gcr.io/$PROJECT_ID/datavis-ci/datavis-github-bot:$COMMIT_SHA', '--cache=true']
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'beta',
        'run',
        'deploy',
        'datavis-github-bot',
        '--image',
        'gcr.io/$PROJECT_ID/datavis-ci/datavis-github-bot:$COMMIT_SHA',
        '--region',
        'us-central1',
      ]
