# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: npm
    directories:
      - "/"
      - "/docs"
      - "/e2e"
      - "/.buildkite"
    schedule:
      interval: weekly
    cooldown:
      default-days: 14
