language: node_js
cache: yarn
script:
  - yarn global add codecov -g
  - yarn build && yarn lint && yarn test --coverage
after_success:
  - codecov
  - yarn semantic-release
before_deploy: yarn storybook:build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  target-branch: gh-pages
  keep-history: false # always force push
  local_dir: .out
