(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[274],{

/***/ "../../storybook/stories/bar/8_with_log_yaxis.story.tsx":
/*!********************************************************************************************************!*\
  !*** /home/runner/work/elastic-charts/elastic-charts/storybook/stories/bar/8_with_log_yaxis.story.tsx ***!
  \********************************************************************************************************/
/*! exports provided: Example */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"Example\", function() { return Example; });\n/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! react */ \"../../node_modules/react/index.js\");\n/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(react__WEBPACK_IMPORTED_MODULE_0__);\n/* harmony import */ var _elastic_charts__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! @elastic/charts */ \"../../packages/charts/src/index.ts\");\n/* harmony import */ var _use_base_theme__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../../use_base_theme */ \"../../storybook/use_base_theme.ts\");\n/*\n * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one\n * or more contributor license agreements. Licensed under the Elastic License\n * 2.0 and the Server Side Public License, v 1; you may not use this file except\n * in compliance with, at your election, the Elastic License 2.0 or the Server\n * Side Public License, v 1.\n */\n\n\n\nconst Example = () => (react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(_elastic_charts__WEBPACK_IMPORTED_MODULE_1__[\"Chart\"], null,\n    react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(_elastic_charts__WEBPACK_IMPORTED_MODULE_1__[\"Settings\"], { legendPosition: _elastic_charts__WEBPACK_IMPORTED_MODULE_1__[\"Position\"].Right, baseTheme: Object(_use_base_theme__WEBPACK_IMPORTED_MODULE_2__[\"useBaseTheme\"])() }),\n    react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(_elastic_charts__WEBPACK_IMPORTED_MODULE_1__[\"Axis\"], { id: \"bottom\", position: _elastic_charts__WEBPACK_IMPORTED_MODULE_1__[\"Position\"].Bottom, title: \"Bottom axis\", showOverlappingTicks: true }),\n    react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(_elastic_charts__WEBPACK_IMPORTED_MODULE_1__[\"Axis\"], { id: \"left2\", domain: {\n            min: NaN,\n            max: NaN,\n            fit: true,\n        }, title: \"Left axis\", position: _elastic_charts__WEBPACK_IMPORTED_MODULE_1__[\"Position\"].Left, tickFormat: (d) => Number(d).toFixed(2) }),\n    react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(_elastic_charts__WEBPACK_IMPORTED_MODULE_1__[\"BarSeries\"], { id: \"bars\", xScaleType: _elastic_charts__WEBPACK_IMPORTED_MODULE_1__[\"ScaleType\"].Linear, yScaleType: _elastic_charts__WEBPACK_IMPORTED_MODULE_1__[\"ScaleType\"].Log, xAccessor: \"x\", yAccessors: ['y'], data: [\n            { x: 1, y: 0 },\n            { x: 2, y: 1 },\n            { x: 3, y: 2 },\n            { x: 4, y: 3 },\n            { x: 5, y: 4 },\n            { x: 6, y: 5 },\n            { x: 7, y: 6 },\n            { x: 8, y: 7 },\n        ] })));\n\n\n//# sourceURL=webpack:////home/runner/work/elastic-charts/elastic-charts/storybook/stories/bar/8_with_log_yaxis.story.tsx?");

/***/ })

}]);