(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[276],{

/***/ "../../storybook/stories/bar/57_test_rect_border_bars.story.tsx":
/*!****************************************************************************************************************!*\
  !*** /home/runner/work/elastic-charts/elastic-charts/storybook/stories/bar/57_test_rect_border_bars.story.tsx ***!
  \****************************************************************************************************************/
/*! exports provided: Example */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"Example\", function() { return Example; });\n/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! react */ \"../../node_modules/react/index.js\");\n/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(react__WEBPACK_IMPORTED_MODULE_0__);\n/* harmony import */ var _elastic_charts__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! @elastic/charts */ \"../../packages/charts/src/index.ts\");\n/* harmony import */ var _use_base_theme__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../../use_base_theme */ \"../../storybook/use_base_theme.ts\");\n/*\n * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one\n * or more contributor license agreements. Licensed under the Elastic License\n * 2.0 and the Server Side Public License, v 1; you may not use this file except\n * in compliance with, at your election, the Elastic License 2.0 or the Server\n * Side Public License, v 1.\n */\n\n\n\nconst Example = () => {\n    return (react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(_elastic_charts__WEBPACK_IMPORTED_MODULE_1__[\"Chart\"], { renderer: \"canvas\" },\n        react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(_elastic_charts__WEBPACK_IMPORTED_MODULE_1__[\"Settings\"], { theme: Object(_use_base_theme__WEBPACK_IMPORTED_MODULE_2__[\"useBaseTheme\"])() }),\n        react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(_elastic_charts__WEBPACK_IMPORTED_MODULE_1__[\"Axis\"], { id: \"count\", title: \"count\", position: _elastic_charts__WEBPACK_IMPORTED_MODULE_1__[\"Position\"].Left }),\n        react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(_elastic_charts__WEBPACK_IMPORTED_MODULE_1__[\"Axis\"], { id: \"x\", title: \"goods\", position: _elastic_charts__WEBPACK_IMPORTED_MODULE_1__[\"Position\"].Bottom }),\n        react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(_elastic_charts__WEBPACK_IMPORTED_MODULE_1__[\"BarSeries\"], { id: \"bars\", name: \"amount\", xScaleType: _elastic_charts__WEBPACK_IMPORTED_MODULE_1__[\"ScaleType\"].Ordinal, xAccessor: \"x\", yAccessors: ['y'], barSeriesStyle: {\n                rectBorder: {\n                    visible: true,\n                    strokeWidth: 10,\n                    stroke: 'black',\n                },\n            }, data: [\n                { x: 'A', y: 0, val: 1222 },\n                { x: 'B', y: 20, val: 1222 },\n                { x: 'C', y: 750, val: 1222 },\n                { x: 'D', y: 854, val: 1222 },\n            ] })));\n};\n\n\n//# sourceURL=webpack:////home/runner/work/elastic-charts/elastic-charts/storybook/stories/bar/57_test_rect_border_bars.story.tsx?");

/***/ })

}]);