(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[294],{

/***/ "../../storybook/stories/goal/25_goal_semantic.story.tsx":
/*!*********************************************************************************************************!*\
  !*** /home/runner/work/elastic-charts/elastic-charts/storybook/stories/goal/25_goal_semantic.story.tsx ***!
  \*********************************************************************************************************/
/*! exports provided: Example */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"Example\", function() { return Example; });\n/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! react */ \"../../node_modules/react/index.js\");\n/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(react__WEBPACK_IMPORTED_MODULE_0__);\n/* harmony import */ var _elastic_charts__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! @elastic/charts */ \"../../packages/charts/src/index.ts\");\n/* harmony import */ var _elastic_charts_src_chart_types_goal_chart_specs_constants__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! @elastic/charts/src/chart_types/goal_chart/specs/constants */ \"../../packages/charts/src/chart_types/goal_chart/specs/constants.ts\");\n/*\n * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one\n * or more contributor license agreements. Licensed under the Elastic License\n * 2.0 and the Server Side Public License, v 1; you may not use this file except\n * in compliance with, at your election, the Elastic License 2.0 or the Server\n * Side Public License, v 1.\n */\n\n\n\nconst subtype = _elastic_charts_src_chart_types_goal_chart_specs_constants__WEBPACK_IMPORTED_MODULE_2__[\"GoalSubtype\"].Goal;\nconst Example = () => {\n    const bandLabels = ['freezing', 'chilly', 'brisk'];\n    const bands = [200, 250, 300];\n    const opacityMap = {\n        '200': 0.2,\n        '250': 0.12,\n        '300': 0.05,\n    };\n    const colorMap = bands.reduce((acc, band) => {\n        const defaultValue = opacityMap[band];\n        acc[band] = `rgba(0, 0, 0, ${defaultValue.toFixed(2)})`;\n        return acc;\n    }, {});\n    const bandFillColor = (x) => colorMap[x];\n    return (react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(_elastic_charts__WEBPACK_IMPORTED_MODULE_1__[\"Chart\"], { className: \"story-chart\" },\n        react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(_elastic_charts__WEBPACK_IMPORTED_MODULE_1__[\"Goal\"], { id: \"spec_1\", subtype: subtype, base: 0, target: 260, actual: 170, \n            // doesn't mess with canvas_renderers.ts\n            bands: bands, ticks: [0, 50, 100, 150, 200, 250, 300], tickValueFormatter: ({ value }) => String(value), bandFillColor: ({ value }) => bandFillColor(value), labelMajor: \"Revenue 2020 YTD  \", labelMinor: \"(thousand USD)  \", centralMajor: \"170\", centralMinor: \"\", angleStart: Math.PI, angleEnd: 0, bandLabels: bandLabels })));\n};\n\n\n//# sourceURL=webpack:////home/runner/work/elastic-charts/elastic-charts/storybook/stories/goal/25_goal_semantic.story.tsx?");

/***/ })

}]);