name: 'Base diff checker'
description: 'Checks commit and file diff between branches'
inputs:
  base-ref:
    description: 'Ref of base branch - not sha'
    required: true
  base-sha:
    description: 'Sha hash of base branch'
    required: true
  head-sha:
    description: 'Sha hash of head branch'
    required: true
  pr-number:
    description: 'Pull request number'
    required: true # required to lookup pr from matrix for target links
  status-context:
    description: 'Commit status context'
    required: false
    default: 'Test merge status'
  limit:
    description: 'Limit for max commits behind'
    required: false
    default: '10'
  silent:
    description: 'Warn on failed check'
    required: false
    default: 'false'
runs:
  using: 'node12'
  main: './index.js'
