#!/usr/bin/env bash

set -euo pipefail

source .buildkite/scripts/utils.sh

cd '.buildkite'

echo '--- Installing buildkite dependencies'

retry 5 15 install_deps

echo '--- Generating buildkite files'

yarn build:bk:types

echo '--- Updating commit status for jobs'

npx ts-node scripts/pre_command.ts
