name: Check for API changes

on: [push, pull_request]

jobs:
  api-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run API-Extractor
        run: yarn api:check
        env:
          CI: true
