name: Publish release

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  release_package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: bahmutov/npm-install@HEAD
      - name: Build check
        run: yarn build
      - name: Lint check
        run: yarn lint
      - name: Prettier check
        run: yarn prettier:check
      - name: TimeZone testing
        run: yarn test:tz --ci
      - name: Testing
        run: yarn test --ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN_GH }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: yarn semantic-release
