name: Lint checks and build

on: [push, pull_request]

jobs:
  build-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: bahmutov/npm-install@HEAD
      - name: Build check
        run: yarn build
      - name: Lint check
        run: yarn lint
      - name: Prettier check
        run: yarn prettier:check
