name: '@elastic/charts CI'

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  ECH_NODE_VERSION: '14.x'

on:
  push:
    branches:
      - "!gh-pages"
  pull_request:
    branches:
      - "!gh-pages"

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      # Runs first to cache node_modules for later runs
      - name: Setup node
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.ECH_NODE_VERSION }}
      - uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true

  eslint:
    name: Eslint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      # ----- Common setup from cache -----
      - name: Setup node
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.ECH_NODE_VERSION }}
      - uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
      # -----------------------------------

      - name: Eslint check
        run: yarn lint

  prettier:
    name: Prettier
    needs: setup
    runs-on: ubuntu-latest
    steps:
      # ----- Common setup from cache -----
      - name: Setup node
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.ECH_NODE_VERSION }}
      - uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
      # -----------------------------------

      - name: Prettier check
        run: yarn prettier:check

  api-check:
    name: API Changes
    needs: setup
    runs-on: ubuntu-latest
    steps:
      # ----- Common setup from cache -----
      - name: Setup node
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.ECH_NODE_VERSION }}
      - uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
      # -----------------------------------

      - name: Run API-Extractor
        run: yarn api:check
      - name: Handle API-Extractor failure
        if: ${{ failure() }}
        uses: LouisBrunner/diff-action@v0.1.0
        with:
          old: packages/charts/api/charts.api.md
          new: packages/charts/tmp/charts.api.md
          mode: deletion
          tolerance: better

  jest:
    name: Unit tests
    needs: setup
    runs-on: ubuntu-latest
    steps:
      # ----- Common setup from cache -----
      - name: Setup node
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.ECH_NODE_VERSION }}
      - uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
      # -----------------------------------

      - name: TimeZone tests
        run: yarn test:tz --ci
      - name: Testing
        run: yarn test --coverage --ci


  build-sb:
    name: Build Storybook
    needs: setup
    runs-on: ubuntu-latest
    steps:
      # ----- Common setup from cache -----
      - name: Setup node
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.ECH_NODE_VERSION }}
      - uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
      # -----------------------------------

      - name: Building storybook
        run: yarn storybook:build
      - name: Save build output
        uses: actions/upload-artifact@v2
        with:
          name: sb-output
          path: .out

  deploy:
    name: Deploy Storybook
    needs: build-sb
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: sb-output

      - name: Deploy master
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .out
          CLEAN: true
