name: Test Playwright

concurrency:
  group: '${{ github.workflow }} - ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  ECH_NODE_VERSION: '16.13.2' # should match version in .nvmrc

on:
  pull_request:
    branches:
      - master

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        shell: python
        run: |
          print("""${{ toJSON(github) }}""")

  e2e-setup:
    name: e2e Setup
    if: github.head_ref == 'playwright'
    runs-on: ubuntu-latest
    outputs:
      test-files: ${{ steps.test-files.outputs.json }}
      playwright-version: ${{ steps.playwright.outputs.version }}
    steps:
      # ----- Common setup from cache -----
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.ECH_NODE_VERSION }}
      # -----------------------------------
      - name: Get test file paths
        id: test-files
        shell: python
        run: |
          import os, glob, json
          os.chdir('e2e/tests')
          files = glob.glob('**/*.test.ts', recursive=True)
          print(f"::set-output name=json::{json.dumps(files)}")
      - name: Get Playwright version
        id: playwright
        run: |
          regex="@playwright/test@(.+)"
          result="$(cd e2e && yarn list --pattern "@playwright/test" --depth=0 | grep playwright/test)"
          if [[ $result =~ $regex ]]
          then
            echo "::set-output name=version::${BASH_REMATCH[1]}"
          else
            echo "Unable to find '@playwright/test' version"
            exit 1
          fi
      - name: Print files
        run: echo "${{ steps.test-files.outputs.json }}"
      - name: Print version
        run: echo "${{ steps.playwright.outputs.version }}"
  e2e:
    name: 'e2e Test / ${{ matrix.test-file }} / ${{ matrix.browser }}'
    if: github.head_ref == 'playwright'
    runs-on: ubuntu-latest
    needs: e2e-setup
    strategy:
      fail-fast: false
      max-parallel: 10 # tbd
      matrix:
        test-file: ${{ fromJSON(needs.e2e-setup.outputs.test-files) }}
        browser: ['chrome', 'safari', 'firefox']
    container:
      image: mcr.microsoft.com/playwright:v${{ needs.e2e-setup.outputs.playwright-version }}-focal
      # volumes:
      #   - ${{ github.workspace }}/e2e:/e2e
    steps:
      - name: Test ls
        run: ls
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install e2e node_modules
        run: cd e2e && yarn install --frozen-lockfile
      - name: Test ls
        run: ls
      - name: Test ls e2e
        run: ls e2e
      - name: Test run
        run: cd e2e && yarn test --project=${{ matrix.browser }} ./tests/${{ matrix.test-file }}
      - name: Test ls e2e
        run: ls e2e
